### ISSUE TITLE
The length of the anomaly scores does not match the length of the test set.

### ISSUE THREAD

**Issue by richard-tang199** [boniolp/ADecimo#1]
Hi! Paul Boniol 
	Thanks for your great work. I wish to use your NormA as a baseline model for comparison purposes. However, you have only provided anomaly scores for NormA on the KDD21 test set. I have noticed, however, that the length of the anomaly scores you have supplied does not align with the length of the test set. For example, the KDD21 UCR_001 test set comprises 44,795 points, yet you have only provided anomaly scores for 30,000 points. This issue is present in other datasets from KDD21 as well. Would you be so kind as to upload the complete set of anomaly scores? Alternatively, would you be willing to share the password for the NormA compression package within the TSB-UAD?  I assure you that it will be used exclusively for academic purposes and that your work will be cited. Thank you for your support!

Qideng Tang
Ph.D candidate
National University of Defense Technology
18907345193@163.com

**Comment by sylligardos** [comment]
Hi Qideng Tang,

I'm Emmanouil Sylligardos, a PhD student working with Paul and a contributor to ADecimo. Let me address your issue.

I understand that you want to use NormA in your experiments and need the complete anomaly scores.

Firstly, the ADecimo repo includes only a sample of data for demo purposes. For the full dataset, please refer to the MSAD repo ([MSAD repository](https://github.com/boniolp/MSAD)). Check the data folder or the README for links to Google Drive with all the data.

Additionally, we can provide you with the password to unlock the NormA zip file for research purposes. Please email me at 'boniol.paul@gmail.com' or 'themis@mi.parisdescartes.fr' and I will send it to you.

I hope this resolves the issue. If you have any further questions, feel free to ask!

Cheers,  
Manos
